apiVersion: v1
description: Trigger OpenFaaS Functions from NATS Pub/Sub
name: nats-connector
version: 0.3.2
sources:
  - https://github.com/openfaas-incubator/nats-connector
home: https://www.openfaas.com
icon: https://raw.githubusercontent.com/openfaas/media/master/OpenFaaS_logo_stacked_opaque.png
keywords:
  - functions
  - service
  - nats
maintainers:
  - name: alexellis
    email: alex@openfaas.com
