
[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"

[[constraint]]
  name = "github.com/openfaas/faas"
  version = "0.9.14"

[[constraint]]
  name = "github.com/openfaas/faas-provider"
  version = "0.9.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.9"

[[constraint]]
  name = "k8s.io/client-go"
  version = "6.0.0"

[prune]
  go-tests = true
  unused-packages = true

