apiVersion: v1
description: Connect OpenFaaS functions to Kafka topics
name: kafka-connector
version: 0.7.3
sources:
- https://github.com/openfaas/faas-netes
home: https://www.openfaas.com
icon: https://raw.githubusercontent.com/openfaas/media/master/OpenFaaS_logo_stacked_opaque.png
keywords:
- openfaas
- serverless
- kafka
- eventdriven
maintainers:
- name: alexellis
  email: alex@openfaas.com
