apiVersion: v1
description: Connect OpenFaaS functions to MQTT topics
name: mqtt-connector
version: 0.4.7
sources:
  - https://github.com/openfaas-incubator/mqtt-connector
home: https://www.openfaas.com
icon: https://raw.githubusercontent.com/openfaas/media/master/OpenFaaS_logo_stacked_opaque.png
keywords:
  - functions
  - eventdriven
  - mqtt
  - iot
maintainers:
  - name: alexellis
    email: alex@openfaas.com
