image: ghcr.io/openfaas/mqtt-connector:0.4.3
replicas: 1

# # Emitter.io example
topic: sample-topic/

# Formal MQTT topic example:
# topic: sample-topic,

# For use with emitter.io
trimChannelKey: false

contentType: application/json

broker: tcp://emitter:8080
clientID: testgoid
authPassword: ""

upstream_timeout: 30s # Maximum duration for an invocation
rebuild_interval: 15s
asyncInvoke: false # Invoke via NATS using the function's asynchronous route
basic_auth: true
gateway_url: http://gateway.openfaas:8080

resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  # limits:
  #   memory: "256Mi"
  #   cpu: "100m"

nodeSelector: {}
tolerations: []
affinity: {}
