apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "connector.name" . }}
    component: kafka-connector
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/name: {{ template "connector.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/component: kafka-connector
    app.kubernetes.io/part-of: openfaas
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: {{ template "connector.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "connector.name" . }}
      component: kafka-connector

  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
      labels:
        app: {{ template "connector.name" . }}
        component: kafka-connector
    spec:
      volumes:
        - name: openfaas-license
          secret:
            secretName: openfaas-license
      {{- if .Values.basic_auth }}
        - name: auth
          secret:
            secretName: basic-auth
      {{- end }}
      {{- if.Values.saslAuth }}
        - name: broker-username
          secret:
            secretName: {{ .Values.brokerUsernameSecret }}
        - name: broker-password
          secret:
            secretName: {{ .Values.brokerPasswordSecret }}
      {{- end }}
      {{- if .Values.caSecret }}
        - name: broker-ca
          secret:
            secretName: {{ .Values.caSecret }}
      {{- end}}
      {{- if .Values.certSecret }}
        - name: broker-cert
          secret:
            secretName: {{ .Values.certSecret }}
      {{- end}}
      {{- if .Values.keySecret }}
        - name: broker-key
          secret:
            secretName: {{ .Values.keySecret }}
      {{- end}}
      containers:
        - name: connector
          image: {{ .Values.image }}
          command:
           - "/usr/bin/kafka-connector"
           - "-license-file=/var/secrets/license/license"
           {{- if.Values.saslAuth }}
           - "-username-file=/var/secrets/broker-username/broker-username"
           - "-password-file=/var/secrets/broker-password/broker-password"
           {{- end }}
           {{- if .Values.tls }}
           - "-tls"
           {{- end }}
           {{- if .Values.caSecret }}
           - "-ca-file=/var/secrets/broker-ca/broker-ca"
           {{- end }}
          {{- if .Values.certSecret }}
           - "-cert-file=/var/secrets/broker-cert/broker-cert"
          {{- end }}
          {{- if .Values.keySecret }}
           - "-key-file=/var/secrets/broker-key/broker-key"
          {{- end }}
          env:
            - name: gateway_url
              value: {{ .Values.gatewayURL | quote }}
            - name: topics
              value: {{ .Values.topics | quote }}
            - name: print_response
              value: {{ .Values.printResponse | quote }}
            - name: print_response_body
              value: {{ .Values.printResponseBody | quote }}
            - name: print_request_body
              value: {{ .Values.printRequestBody | quote }}
            - name: asynchronous_invocation
              value: {{ .Values.asyncInvocation | quote }}
            {{- if .Values.basic_auth }}
            - name: basic_auth
              value: "true"
            - name: secret_mount_path
              value: "/var/secrets"
            {{- end }}
            - name: broker_host
              value: {{ .Values.brokerHost | quote }}
            {{- if .Values.upstreamTimeout }}
            - name: upstream_timeout
              value: {{ .Values.upstreamTimeout | quote }}
            {{- end }}
            {{- if .Values.rebuildInterval }}
            - name: rebuild_interval
              value: {{ .Values.rebuildInterval | quote }}
            {{- end }}
            - name: content_type
              value: {{ .Values.contentType | quote }}
            {{- if .Values.group }}
            - name: group
              value: {{ .Values.group | quote }}
            {{- end }}
            {{- if .Values.sessionLogging }}
            - name: log_sessions
              value: {{ .Values.sessionLogging | quote }}
            {{- end }}
            {{- if .Values.maxBytes }}
            - name: max_bytes
              value: {{ .Values.maxBytes | quote }}
            {{- end }}
            {{- if .Values.initialOffset }}
            - name: initial_offset
              value: {{ .Values.initialOffset | quote }}
            {{- end }}
            - name: "debug"
              value: "{{ .Values.logs.debug }}"
            - name: "log_encoding"
              value: "{{ .Values.logs.format }}"
          resources:
            {{- .Values.resources | toYaml | nindent 12 }}
          volumeMounts:
            - name: openfaas-license
              readOnly: true
              mountPath: "/var/secrets/license"
          {{- if .Values.basic_auth }}
            - name: auth
              readOnly: true
              mountPath: "/var/secrets"
          {{- end }}
          {{- if.Values.saslAuth }}
            - name: broker-username
              readOnly: true
              mountPath: "/var/secrets/broker-username"
            - name: broker-password
              readOnly: true
              mountPath: "/var/secrets/broker-password"
          {{- end }}

          {{- if .Values.caSecret }}
            - name: broker-ca
              readOnly: true
              mountPath: "/var/secrets/broker-ca"
          {{- end}}

          {{- if .Values.certSecret }}
            - name: broker-cert
              readOnly: true
              mountPath: "/var/secrets/broker-cert"
          {{- end }}
          {{- if .Values.keySecret }}
            - name: broker-key
              readOnly: true
              mountPath: "/var/secrets/broker-key"
          {{- end }}

    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
