apiVersion: v1
description: OpenFaaS - Serverless Functions Made Simple
name: openfaas
version: 6.0.1
sources:
- https://github.com/openfaas/faas
- https://github.com/openfaas/faas-netes
home: https://www.openfaas.com
icon: https://raw.githubusercontent.com/openfaas/media/master/OpenFaaS_logo_stacked_opaque.png
keywords:
- functions
- service
maintainers:
- name: alexellis
  email: alex@openfaas.com
- name: lucasroesler
  email: roesler.lucas@gmail.com
- name: stefanprodan
  email: stefan.prodan@gmail.com
