basic_auth: true

gateway:
  image: openfaas/gateway:0.18.2-arm64
  directFunctions: true

faasnetes:
  image: openfaas/faas-netes:0.9.7-arm64

queueWorker:
  image: openfaas/queue-worker:0.8.1-arm64

prometheus:
  image: prom/prometheus:v2.11.0
  resources:
    requests:
      memory: "125Mi"

alertmanager:
  image: prom/alertmanager:v0.18.0

faasIdler:
  image: openfaas/faas-idler:0.2.0-arm64

basicAuthPlugin:
  image: openfaas/basic-auth-plugin:0.18.2-arm64
  replicas: 1

ingressOperator:
  create: false
