basic_auth: true

nodeSelector:
  beta.kubernetes.io/arch: arm64

gateway:
  image: openfaas/gateway:0.18.17-arm64
  directFunctions: true

oauth2Plugin:
  enabled: false

faasnetes:
  image: openfaas/faas-netes:0.10.5-arm64

operator:
  image: openfaas/faas-netes:0.10.5-arm64
  create: false

queueWorker:
  image: openfaas/queue-worker:0.11.0-arm64

prometheus:
  image: prom/prometheus:v2.11.0
  resources:
    requests:
      memory: "125Mi"

alertmanager:
  image: prom/alertmanager:v0.18.0

faasIdler:
  image: openfaas/faas-idler:0.3.0-arm64

basicAuthPlugin:
  image: openfaas/basic-auth-plugin:0.18.17-arm64
  replicas: 1

ingressOperator:
  create: false

# Unfortunately the exporter is not multi-arch (yet)
nats:
  metrics:
    enabled: false
