{{- if .Values.exposeServices }}
{{- if eq .Values.operator.create false }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "openfaas.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: faas-netesd
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: faas-netesd-external
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ template "openfaas.name" . }}
{{- end }}
{{- end }}
