{{- $functionNs := default .Release.Namespace .Values.functionNamespace }}

{{/* Generate role rules */}}
{{ define "openfaas.role.rules" }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
  - apiGroups:
      - extensions
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
{{ end }}

{{- if .Values.rbac }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: {{ template "openfaas.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: faas-controller
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: faas-controller
  namespace: {{ .Release.Namespace | quote }}
{{ include "openfaas.role.rules" . }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: {{ template "openfaas.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: faas-controller
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: faas-controller
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: faas-controller
subjects:
  - kind: ServiceAccount
    name: faas-controller
    namespace: {{ .Release.Namespace | quote }}
---
{{- if (ne .Release.Namespace $functionNs) }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels:
    app: {{ template "openfaas.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: faas-controller
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: faas-controller
  namespace: {{ $functionNs | quote }}
{{ include "openfaas.role.rules" . }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels:
    app: {{ template "openfaas.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: faas-controller
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: faas-controller-fn
  namespace: {{ $functionNs | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: faas-controller
subjects:
  - kind: ServiceAccount
    name: faas-controller
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
---
{{- end }}
