apiVersion: v1
description: Trigger OpenFaaS functions from PostgreSQL
name: postgres-connector
version: 0.1.0
sources:
- https://github.com/openfaas/faas-netes
home: https://www.openfaas.com
icon: https://raw.githubusercontent.com/openfaas/media/master/OpenFaaS_logo_stacked_opaque.png
keywords:
- openfaaspro
- serverless
- postgres
- events
maintainers:
- name: alexellis
  email: alex@openfaas.com
