apiVersion: v2
description: Federated Gateway for OpenFaaS service providers
name: federated-gateway
version: 0.1.0
home: https://openfaas.com
keywords:
- openfaas
- oidc
- proxy
maintainers:
- name: alexellis
  email: alex@openfaas.com
- name: welteki
  email: han@openfaas.com
