apiVersion: v1
description: Build OpenFaaS functions via a REST API
name: pro-builder
version: 0.4.2
sources:
- https://github.com/openfaas/faas-netes
home: https://www.openfaas.com
icon: https://raw.githubusercontent.com/openfaas/media/master/OpenFaaS_logo_stacked_opaque.png
keywords:
- imagebuilder
- functionbuilder
- builder
- functions
maintainers:
- name: alexellis
  email: alex@openfaas.com
